language: node_js
node_js:
  - "7"
cache:
  directories:
    - "node_modules"
script:
  - npm install jshint
  - jshint gen.js

deploy:
  provider: pages
  cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master