language: node_js
node_js:
  - "7"
cache:
  directories:
    - "node_modules"
script:
  - npm install eslint babel-eslint babel-cli
  - "npm run lint"

deploy:
  provider: pages
  cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master