name: "ESLint"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v2.5.1
      with:
        node-version: 12.x
      
    - name: Install ESlint deps
      run: yarn
    - name: Lint JS with ESlint
      run: |
        yarn global add eslint
        export PATH="$(yarn global bin):$PATH"
        eslint gen.js
