name: "CI"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1.4.2
      
    - name: Install ESlint
      run: |
        yarn
        yarn global add eslint
    - name: Lint JS with ESlint
      run: eslint gen.js
      
    - name: Lint CSS with CSSLint
      run: |
        yarn global add csslint
        csslint style.css
