name: "Lint CSS"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 15.x
      uses: actions/setup-node@v2.1.2
      with:
        node-version: 15.0.1
      
    - name: Lint CSS via Gulp
      run: |
        yarn
        yarn global add gulp-cli
        export PATH="$(yarn global bin):$PATH"
        gulp compileSASS
